version: 0.2

phases:
  install:
    commands:
      - echo "Starting installation"
      - cd my-beanstalk-app
      - echo "Installing Node.js dependencies"
      - npm install

  build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: my-beanstalk-app
